name=ESPUI
version=2.3.4
author=Lukas Bachschwell
maintainer=Lukas Bachschwell <lukas@lbsfilm.at>
sentence=ESP32, ESP8266, RP2040, and RP2350 Web Interface Library
paragraph=A simple library that implements a web graphical user interface for ESP32, ESP8266, RP2040, and RP2350. It is simple to use and works side by side with your sketch.
category=Communication
url=https://github.com/s00500/ESPUI
architectures=esp32,esp8266,rp2040,rp2350
depends=ArduinoJson,ESPAsyncWebServer
